extends Node2D

@onready var detective_pk: CharacterBody2D = $Characters/DetectivePK
@onready var player: CharacterBody2D = $Characters/Player

# DetectivePK Super Bowl vars
@export var reported_letter: bool = false
@export var num_h: int # number of h in the letter generated by the bot (depends on username)
@export var found_culprit: bool = false
@export var witness_username: String # Discord username of witness from bot (used to calculate code below)
@export var completed: bool = false
@export var certificate_text: String # text displayed for certificate of completion


func _ready() -> void:
	pass


func on_player_interaction_area_entered(area: Area2D):
	if area.name == "BumpIntoPK": # PK intro cutscene
		Global.cutscene_started.emit()
		
		# give detective PK his sprites and animations
		var pk_sprite: AnimatedSprite2D = preload("res://sprites/character_sprite.tscn") \
		.instantiate()
		pk_sprite.sprite_frames = pk_sprite.sprite_frames.duplicate(true)
		var replacement_spritesheet: Texture2D = preload("res://sprites/DetectivePK.png")
		pk_sprite.swap_textures(replacement_spritesheet)
		
		detective_pk.add_child(pk_sprite)
		
		# get pushed by detective pk as he leaves the police station
		var distance_pushed: float = 0
		# PK becomes visible and pushes you as leaving the police station outside to where you are
		var distance_pk_moved: float = 0
		detective_pk.visible = true
		while distance_pushed < 40:
			player.position.y += get_process_delta_time() * 50
			distance_pushed += get_process_delta_time() * 50
			while distance_pk_moved < 10:
				detective_pk.position.y += get_process_delta_time() * 50
				distance_pk_moved += get_process_delta_time() * 50
		
		detective_pk.get_node("CollisionShape2D").set_deferred("disabled", false)
		detective_pk.get_node("InteractionHitbox").set_deferred("monitorable", true)
		player.sfx_audio.stream = preload("res://audio/thud.wav")
		DialogueManager.show_dialogue_balloon(preload("res://dialogues/detective_pk_intro.dialogue"), "", [self, player])
		
	elif !found_culprit and reported_letter and area.name == "MysteriousH": # Mysterious h letter translation cutscene
		# calculate unique number of h in letter as given by the discord bot to report to h
		num_h = 0
		for c in Global.username:
			num_h += ord(c)
		num_h = ceil(num_h / 1000.0) + 167
		DialogueManager.show_dialogue_balloon(preload("res://dialogues/mysterious_h_letter.dialogue"), "", [self, player])


func on_player_input(event: InputEvent) -> void:
	if not player.interacting:
		if event.is_action_pressed("interact"):
			var interactions: Array[Area2D] = player.interaction_hitbox.get_overlapping_areas()
			if len(interactions) > 0:
				# DETECTIVE PK INTERACTIONS
				if len(interactions) > 1 and (interactions[0].name == "BeachForestSign" and interactions[0].name == "OtherSign" or interactions[0].name == "OtherSign" and interactions[1].name == "BeachForestSign"):
					DialogueManager.show_dialogue_balloon(preload("res://dialogues/beach_forest_and_other_sign.dialogue"))
				elif interactions[0].name.begins_with("Area2D"): # not police station sign
					Global.character_look_at(get_node("/root/DetectivePK/Characters/Player"), interactions[0])
					DialogueManager.show_dialogue_balloon(preload("res://dialogues/not_police_station.dialogue"))
				elif interactions[0].name == "PoliceStationSign":
					DialogueManager.show_dialogue_balloon(preload("res://dialogues/police_station.dialogue"))
				elif interactions[0].name == "BeachForestSign":
					DialogueManager.show_dialogue_balloon(preload("res://dialogues/beach_forest_sign.dialogue"))
				elif interactions[0].name == "OtherSign":
					DialogueManager.show_dialogue_balloon(preload("res://dialogues/other_sign.dialogue"))
				elif interactions[0].get_parent().name == "DetectivePK":
		
					if reported_letter:
						DialogueManager.show_dialogue_balloon(preload("res://dialogues/detective_pk_after_found_letter.dialogue"), "", [self, player])
					else:
						DialogueManager.show_dialogue_balloon(preload("res://dialogues/detective_pk_found_letter.dialogue"), "", [self, player])
				elif interactions[0].get_parent().name == "Art":
					DialogueManager.show_dialogue_balloon(preload("res://dialogues/art.dialogue"), "", [self, player])
					
# have PK enter in from the bottom off screen (DETECTIVE PK SPECIFIC)
func enter_pk():
	detective_pk.get_node("AnimatedSprite2D").play("walk_up")
	const DISTANCE_AWAY: float = 100
	detective_pk.get_node("CollisionShape2D").disabled = true
	detective_pk.position = player.position + Vector2(0, DISTANCE_AWAY)
	var distance_pk_moved: float = 0
	while distance_pk_moved < DISTANCE_AWAY - 20:
		detective_pk.position.y -= get_process_delta_time() * player.speed * 1.5
		distance_pk_moved += get_process_delta_time() * player.speed * 1.5
		await get_tree().process_frame  # ← LET GODOT RENDER
		
	detective_pk.get_node("CollisionShape2D").set_deferred("disabled", false)
	detective_pk.get_node("AnimatedSprite2D").play("idle_up")
	
# have Art enter in from the bottom off screen (DETECTIVE PK SB SCANDAL SPECIFIC)
func enter_art():
	
	const DISTANCE_AWAY: float = 100
	var art: CharacterBody2D = get_node("Characters/Art")
	# give Art his sprites and animations
	var art_sprite: AnimatedSprite2D = preload("res://sprites/character_sprite.tscn") \
	.instantiate()
	art_sprite.sprite_frames = art_sprite.sprite_frames.duplicate(true)
	var replacement_spritesheet: Texture2D = preload("res://sprites/Art.png")
	art_sprite.swap_textures(replacement_spritesheet)
	
	art.add_child(art_sprite)
	
	art.get_node("AnimatedSprite2D").play("walk_up")
	art.position = player.position + Vector2(67,DISTANCE_AWAY)
	var distance_art_moved: float = 0
	while distance_art_moved < DISTANCE_AWAY - 40:
		art.position.y -= get_process_delta_time() * player.speed * 0.75
		distance_art_moved += get_process_delta_time() * player.speed * 0.75
		await get_tree().process_frame  # ← LET GODOT RENDER
		
	art.get_node("CollisionShape2D").set_deferred("disabled", false)
	art.get_node("InteractionHitbox").set_deferred("monitorable", true)
	art.get_node("AnimatedSprite2D").play("idle_up")
# detective pk will hit a jig (DETECTIVE PK SPECIFIC)
func pk_jig():
	var pk_sprite: AnimatedSprite2D = detective_pk.get_node("AnimatedSprite2D")
	pk_sprite.play("jig_down")
	await pk_sprite.animation_finished
	
# calculate witness code received by the bot to verify with PK (DETECTIVE PK SPECIFIC)
func calculate_witness_code() -> int:
	var witness_code:int = 67
	var char_count: int = 3 if min(len(Global.username), len(witness_username)) >= 3 else  min(len(Global.username), len(witness_username))
	var s1: String = Global.username.substr(0,char_count)
	var s2: String = witness_username.substr(0,char_count)
	for i in range(len(s1)):
		witness_code += ord(s1[i]) + ord(s2[i])
	return witness_code
